# Local Network Tests, E2E workflow.
#
# Runs client tests against latest node release

name: Local Network Tests

on: pull_request

env:
  # Run all cargo commands with --verbose.
  CARGO_TERM_VERBOSE: true
  RUST_BACKTRACE: 1
  # Deny all compiler warnings.
  RUSTFLAGS: "-D warnings"
  NODE_COUNT: "11" # this is a single section

jobs:
  tests:
    name: E2E tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # TODO: x-platform
        os: [ubuntu-latest]
        # os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2

      # Install Rust and required components
      - uses: actions-rs/toolchain@v1
        name: Install Rust & required components
        with:
          profile: minimal
          toolchain: stable
          override: true


      # Cache.
      - name: Cargo cache registry, index and build
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-cache-${{ hashFiles('**/Cargo.lock') }}

      # If we need a custom CLI version (testing out new APIs/messages etc,
      # we'll need to supply a modified script here I suppose)
      - name: Download Safe CLI
        run: curl -so- https://sn-api.s3.amazonaws.com/install.sh | bash

      - name: Check Safe CLI version
        run: ~/.safe/cli/safe -V

      - name: Install sn_node
        run: ~/.safe/cli/safe node install

      - name: Check sn_node Version
        run: ~/.safe/cli/safe node bin-version

      - name: Start local network
        run: ~/.safe/cli/safe node run-baby-fleming --nodes $NODE_COUNT

      - name: E2E Tests Against local network
        shell: bash
        run: cargo test --release blob_apis -- --test-threads=1

      # TODO: Upload all logs as artifacts....
      - name: Node Logs
        run: |
          ls $HOME/.safe/node/baby-fleming-nodes
          cat $HOME/.safe/node/baby-fleming-nodes/sn-node-genesis/sn_node.log
        if: failure()
